Add feature to also redact custom link text
sobjornstad/tzk pull request #5
Opened 2022-03-12 00:59 UTC by jacobkiers

Hi, this is the second of the changes that I made when setting up my wiki.

It is possible that a private person is linked to in a tiddler with the syntax `[[Jane|MsJaneDoe]]`. Up to now, the text of the link was not redacted, which could lead to unintentional privacy leaks.

Therefore, a new parameter `replace_text` is introduced for the `replace_private_people` builder. When that is set to `True`, then the link text is also replaced with the initials.

This feature is also licensed with the same license as this project.

Thanks a lot!

2022-03-14 00:06 UTC, sobjornstad commented
Hmm, I'm not so sure about the advisability of this option.

* You could have anything in the link text. It might have nothing to do with the person's name, and then the replaced sentence would be nonsense.
* Maybe that's a worthwhile tradeoff to you. But on the flip side, you can have “Jane” outside of a link, and this won't redact it. So I'm worried this might give a false sense of confidence.

I don't think this is inherently a bad feature, and overall I'd rather have more options than fewer options if they're useful to someone, but I think the documentation you've included is making promises it can't fulfill. I can update that myself, but I'd be interested to know if you have any further thoughts on this.

On a different note, there are two places where you've written `line` instead of `lines[i]` – is that a mistake? I don't see a variable `line` in this scope and am not sure why it would have changed.

2022-03-14 17:36 UTC, jacobkiers commented
Thank you for your feedback.

I do not have the time yet to reply with code for this, because it needs a lot more care than the other one, but I did want to reply to your points in text.

> Hmm, I'm not so sure about the advisability of this option.
> 
>     * You could have anything in the link text. It might have nothing to do with the person's name, and then the replaced sentence would be nonsense.

I work a lot in fields that require fairly strict confidentiality, so I tend to be very careful when writing this that might end up becoming public. Even when writing initially private notes.

The PrivateChunk feature already helps a lot with that, that was a great invention.

Either way, I tend to ensure that person's names are actually in the link text, maybe in abbreviated form. So this is no issue for me.

>     * Maybe that's a worthwhile tradeoff to you. But on the flip side, you can have “Jane” outside of a link, and this won't redact it. So I'm worried this might give a false sense of confidence.

Yes, I can see your point. For the same reason this is also no issue for me, but maybe this can be clarified.

> 
> I don't think this is inherently a bad feature, and overall I'd rather have more options than fewer options if they're useful to someone, but I think the documentation you've included is making promises it can't fulfill. I can update that myself, but I'd be interested to know if you have any further thoughts on this.

I'm thinking of renaming `replace_text` with `replace_link_text`, since that would make the purpose clearer. And adding some stronger language with a warning in the documentation of it would be useful too.

Would that be enough for you?

2022-03-14 17:36 UTC, jacobkiers commented
Taking this one separately:

> On a different note, there are two places where you've written `line` instead of `lines[i]` – is that a mistake? I don't see a variable `line` in this scope and am not sure why it would have changed.

Yes, that is a mistake. Apparently I based it off some earlier code. I did notice that, and rebased, but apparently I missed these two places.

In my testing everything worked fine, but I may have not tested all cases, so it could easily have slipped my notice. Easy to fix, and I will reread the changes next round to make sure I caught all.

2022-03-15 01:54 UTC, sobjornstad commented
Yep, I think the rename and a good explanation in the docstring should be enough. Maybe make the link text something other than just `John` (e.g., `John says`) and show what the full replacement would be in both link text and target.

We could also include a `warning` Sphinx directive mentioning both this parameter and the function as a whole, pointing out that it only handles links and thus doesn't ensure all relevant references will be removed from the tiddler without the user's cooperation, e.g.:

```
:param initialer: bla bla bla
:param replace_link_text: bla bla bla

.. warning:
    Enabling `replace_link_text` does not ensure all references to names are removed from your output because...
```

(You can see an [example of what that looks like](https://tzk.readthedocs.io/en/latest/configuration.html#committing) – this one's a note rather than a warning, but it looks basically the same.)

2022-03-15 23:01 UTC, jacobkiers commented
I have updated this with the changes as requested. Could you review again place?

2022-03-16 14:22 UTC, sobjornstad requested changes

2022-03-16 14:22 UTC, sobjornstad commented on tzk/builders.py
> +def replace_private_people(initialer: Callable[[str], str] = None, replace_link_text = False) -> None:
Please use type annotation: `replace_link_text: bool = False`

2022-03-16 14:22 UTC, sobjornstad commented on tzk/builders.py
> +                            end = lines[i].find('|' + replace_person + ']]')
Upon testing, the approach with `find` has an issue: if there are two links with different target and text to the same person in the line, it replaces only the first one. I had this issue with the other branches earlier, too.

I see that even before the PR, this still behaves incorrectly if there's a CamelCase link and a `[[bracketed]]` link -- though it doesn't create a leak, it does replace the CamelCase link with `Initials|PrivatePerson`, which isn't very pretty.

Let me take a few minutes to think about whether we can structure this function a little bit differently to avoid this entirely.

2022-03-16 14:27 UTC, sobjornstad commented
OK, I rewrote the privatize routine on the branch `new-private-person-replacement-logic` – can you try rebasing this over there? You might honestly just want to start a new PR and copy your changes over (or do a `git reset --hard` to the branch and force-push if you want to keep the same PR, as it's probably going to be a very ugly merge.

I think you can still slot in your changes in roughly the same way, except it'll be in the `_privatize_line()` helper function instead of the builder itself. They'll be under the line `elif is_textual_bracketed_link(start_idx, end_idx)`, and as you can see, you have access to the start and end index of the specific occurrence of the person's name being replaced already, and whatever code you put there will be called repeatedly for every occurrence of the name.

That function has a `replace_link_text` parameter, but I haven't wired it up to anything yet so it's *always* going to be False – you'll also need to change the builder so that it has this parameter and passes it into the call to `_privatize_line`.

I created [doctests](https://pythontest.com/framework/doctest/doctest-introduction/) for the `_privatize_line()` function because this was a real pain to get right. You can run them with `python -m doctest builders.py` (there won't be any output if they all pass), and feel free to add additional ones for the logic you're adding.

Thanks for your work on this so far!

2022-03-16 20:16 UTC, jacobkiers commented
That is some next-level code.

I would need some time to really look at it. I'll probably not going to be able to do so during the next few days, but I think during the weekend is possible.

2022-03-16 21:15 UTC, sobjornstad commented
> That is some next-level code.

Haha, this was *such* a pain to write. One of those rabbit holes where it looks like it should be incredibly simple but there are so many edge cases and fussy details it takes 2 hours.

I don't think your snippet should have gotten any harder though, so there's that. No hurry.

2022-03-22 22:46 UTC, jacobkiers commented
I rebased the code onto your new branch with the new privatization logic. I have also rewired the `replace_link_text` functionality into `replace_private_persons`.

The doctests succeed and a test on my private wiki works as well. So I think it is okay now. 

Could you review again?

2022-03-26 17:43 UTC, sobjornstad commented
Looks good, thanks!

2022-03-26 17:43 UTC, merged

2022-03-26 17:46 UTC, sobjornstad commented
Hmm, @jacobkiers  it looks to me like you force-pushed the wrong thing to this branch. It's this commit that you actually wanted  merged in the end right?

https://github.com/jacobkiers/tzk/commit/dcac80c5aced8b283346145008cd07efeb6ae5af

2022-03-26 17:55 UTC, jacobkiers commented
Yes, this was the correct one. I based it on your refactor.

Thanks!

2022-03-26 17:58 UTC, jacobkiers commented
Oh, I see what you mean now. The commit you mentioned was the right one, yes, dcac80c.

2022-03-27 20:16 UTC, sobjornstad commented
Re-merged in https://github.com/sobjornstad/tzk/commit/8fb496bbfe9e6585a5d98fa5e16979f63f34d6da.